
export const GET_VISIT_SAGA = 'GET_VISIT_SAGA';
export const GET_VISIT_START = 'GET_VISIT_START';
export const GET_VISIT_SUCCESS = 'GET_VISIT_SUCCESS';
export const GET_VISIT_FAIL = 'GET_VISIT_FAIL';

export const EDIT_VISIT_SAGA = 'EDIT_VISIT_SAGA';
export const EDIT_VISIT_START = 'EDIT_VISIT_START';
export const EDIT_VISIT_SUCCESS = 'EDIT_VISIT_SUCCESS';
export const EDIT_VISIT_FAIL = 'EDIT_VISIT_FAIL';
