// export const GET_BOOKING_SAGA = 'GET_BOOKING_SAGA';
// export const GET_BOOKING_START = 'GET_BOOKING_START';
// export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
// export const GET_BOOKING_FAIL = 'GET_BOOKING_FAIL';

// export const GET_BOOKING1_SAGA = 'GET_BOOKING1_SAGA';   

export const GET_VISIT_SAGA = 'GET_VISIT_SAGA';
export const GET_VISIT_START = 'GET_VISIT_START';
export const GET_VISIT_SUCCESS = 'GET_VISIT_SUCCESS';
export const GET_VISIT_FAIL = 'GET_VISIT_FAIL';

export const EDIT_VISIT_SAGA = 'EDIT_VISIT_SAGA';
export const EDIT_VISIT_START = 'EDIT_VISIT_START';
export const EDIT_VISIT_SUCCESS = 'EDIT_VISIT_SUCCESS';
export const EDIT_VISIT_FAIL = 'EDIT_VISIT_FAIL';

export const DELETE_VISIT_SAGA = 'DELETE_VISIT_SAGA';
export const DELETE_VISIT_START = 'DELETE_VISIT_START';
export const DELETE_VISIT_SUCCESS = 'DELETE_VISIT_SUCCESS';
export const DELETE_VISIT_FAIL = 'DELETE_VISIT_FAIL';

// export const ADD_BOOKING_SAGA = 'ADD_BOOKING_SAGA';
// export const ADD_BOOKING_START = 'ADD_BOOKING_START';
// export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
// export const ADD_BOOKING_FAIL = 'ADD_BOOKING_FAIL';

// export const EDIT_BOOKING_SAGA = 'EDIT_BOOKING_SAGA';
// export const EDIT_BOOKING_START = 'EDIT_BOOKING_START';
// export const EDIT_BOOKING_SUCCESS = 'EDIT_BOOKING_SUCCESS';
// export const EDIT_BOOKING_FAIL = 'EDIT_BOOKING_FAIL';

// export const DELETE_BOOKING_SAGA = 'DELETE_BOOKING_SAGA';
// export const DELETE_BOOKING_START = 'DELETE_BOOKING_START';
// export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
// export const DELETE_BOOKING_FAIL = 'DELETE_BOOKING_FAIL';

// export const COLLECT_PAYMENT_SAGA = 'COLLECT_PAYMENT_SAGA';
// export const COLLECT_PAYMENT_START = 'COLLECT_PAYMENT_START';
// export const COLLECT_PAYMENT_SUCCESS = 'COLLECT_PAYMENT_SUCCESS';
// export const COLLECT_PAYMENT_FAIL = 'COLLECT_PAYMENT_FAIL';